server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://loki-ext.myorganicapps.com/loki/api/v1/push
    headers:
      CF-Access-Client-Id: "${LOKI_CF_ACCESS_CLIENT_ID}"
      CF-Access-Client-Secret: "${LOKI_CF_ACCESS_CLIENT_SECRET}"
    external_labels:
      host: PROD-PostHog-Platform
      env: PROD

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: var_logs
          __path__: /var/log/*log

  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
    pipeline_stages:
      - docker: {}
      - static_labels:
          job: "docker_logs"
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_id']
        regex: '(.*)'
        target_label: 'container_id'
